#   Script for removing records with stop codons and frameshifts
#   Script expects as inputs a file generated by MiXCR's "exportClones()" function,
#       which has this schema:
#
#       Clone count    Clone fraction  Clonal sequence(s)  Clonal sequence quality(s)  All V hits  All D hits  All J hits  All C hits  All V alignment All D alignment All J alignment All C alignment N. Seq. FR1 Min. qual. FR1  N. Seq. CDR1    Min. qual. CDR1 N. Seq. FR2 Min. qual. FR2  N. Seq. CDR2    Min. qual. CDR2 N. Seq. FR3 Min. qual. FR3  N. Seq. CDR3    Min. qual. CDR3 N. Seq. FR4 Min. qual. FR4  AA. seq. FR1    AA. seq. CDR1   AA. seq. FR2    AA. seq. CDR2   AA. seq. FR3    AA. seq. CDR3   AA. seq. FR4    Best V hit  Best J hit

#   Ensures that numeric outputs are not expressed in scientific notation
options(scipen=999);

remove.records <- function(input.file)    {

    #   Specify characters to search for here.
    #       Note that since "grep()" is used to identify records containing these
    #       special characters, escapes may be required (e.g. "\\*" instead of "*").
    special.characters <- c("\\*", "_");

    #   read in file
    clonotypes <- read.delim(input.file, 
        check.names=FALSE,
        stringsAsFactors=FALSE);
    #   identify records containing the special character
    for(i in 1:length(special.characters))  {
        aas <- clonotypes$"AA. seq. CDR3";
        indices.to.remove <- integer();
        indices.to.remove <- grep(special.characters[i], aas);
        #   remove records
        if(length(indices.to.remove > 0))   {
            clonotypes <- clonotypes[-indices.to.remove,];
        }   #   fi
    }   #   for i 
    #   write output to file

    output.file.name <- sub("[.][^.]*$", "", basename(input.file));
    output.file.name <- paste(output.file.name, "_no_fssc.txt", sep="");
	output.file.name <- file.path(dirname(input.file), output.file.name);

    write.table(clonotypes, 
        file=output.file.name, 
        row.names=FALSE,
        sep="\t",
        quote=FALSE);

}   #   remove.records()


#   This is the original function, which took as input files formatted for use in
#       VDJTools.  Such files had this schema:
#
#               #count  freq    cdr3nt  cdr3aa  v   d   j   VEnd    DStart  DEnd    JStart
#
#remove.records <- function(input.file)    {
#
#    #   Specify characters to search for here.
#    #       Note that since "grep()" is used to identify records containing these
#    #       special characters, escapes may be required (e.g. "\\*" instead of "*").
#    special.characters <- c("\\*", "_");
#
#    #   read in file
#    clonotypes <- read.delim(input.file, stringsAsFactors=FALSE);
#    #   identify records containing the special character
#    for(i in 1:length(special.characters))  {
#        aas <- clonotypes$cdr3aa;
#        indices.to.remove <- integer();
#        indices.to.remove <- grep(special.characters[i], aas);
#        #   remove records
#        if(length(indices.to.remove > 0))   {
#            clonotypes <- clonotypes[-indices.to.remove,];
#        }   #   fi
#    }   #   for i 
#    #   write output to file
#
#    colnames(clonotypes)[1] <- "#count";
#    output.file.name <- sub("[.][^.]*$", "", basename(input.file));
#    output.file.name <- paste(output.file.name, "_no_fssc.txt", sep="");
#
#    write.table(clonotypes, 
#        file=output.file.name, 
#        row.names=FALSE,
#        sep="\t",
#        quote=FALSE);
#
#}   #   remove.records()
#
