#   Script for flagging and/or removing records with stop codons and frameshifts
#   
#   Set the value of the remove.clone.table parameter to indicate whether clonotypes
#       containing stop codons and frameshifts should be removed
#
#   Script expects as inputs a file generated by MiXCR's "exportClones()" function,
#       which has this schema:
#
#       Clone count    Clone fraction  Clonal sequence(s)  Clonal sequence quality(s)  All V hits  All D hits  All J hits  All C hits  All V alignment All D alignment All J alignment All C alignment N. Seq. FR1 Min. qual. FR1  N. Seq. CDR1    Min. qual. CDR1 N. Seq. FR2 Min. qual. FR2  N. Seq. CDR2    Min. qual. CDR2 N. Seq. FR3 Min. qual. FR3  N. Seq. CDR3    Min. qual. CDR3 N. Seq. FR4 Min. qual. FR4  AA. seq. FR1    AA. seq. CDR1   AA. seq. FR2    AA. seq. CDR2   AA. seq. FR3    AA. seq. CDR3   AA. seq. FR4    Best V hit  Best J hit

#   Ensures that numeric outputs are not expressed in scientific notation
options(scipen=999);

process.frameshifts.stop.codons <- function(input.file.path, remove.clone.table=FALSE)    {

    #   Specify characters to search for here.
    #       Note that since "grep()" is used to identify records containing these
    #       special characters, escapes may be required (e.g. "\\*" instead of "*").
    special.characters <- c("\\*", "_");

    #   read in file
    clone.table <- read.delim(input.file.path, 
        check.names=FALSE,
        stringsAsFactors=FALSE);
    
    #   Append additional columns to data.frame
    clone.table$"Contains frameshift or stop codon" <- 0;
    clone.table$"Adjusted clone fraction" <- 0;
    
    #   identify records containing the special character, and flag them
    for(i in 1:length(special.characters))  {
        aas <- clone.table$"AA. seq. CDR3";
        dirty.clone.indices <- integer();
        dirty.clone.indices <- grep(special.characters[i], aas);
        #   flag them
        if(length(dirty.clone.indices) > 0)   {
            clone.table[dirty.clone.indices,]$"Contains frameshift or stop codon" <- 1;
        }   #   fi
    }   #   for i 

    #   Adjust clone fractions
    clean.clone.indices <- which(clone.table$"Contains frameshift or stop codon" == 0);
    sum.clean.clones <- sum(clone.table[clean.clone.indices,]$"Clone fraction");
    clone.table[clean.clone.indices,]$"Adjusted clone fraction" <- clone.table[clean.clone.indices,]$"Clone fraction" / sum.clean.clones;
    
    #   If remove.clone.table is TRUE, then remove the appropriate records
    #       and copy the values for "Adjusted clone fraction" values to the
    #       "Clone fraction" column
    if(remove.clone.table)  {
        #   remove records
        indices.to.remove <- which(clone.table$"Contains frameshift or stop codon" == 1);
        if(length(indices.to.remove > 0))   {
            clone.table <- clone.table[-indices.to.remove,];
        }   #   fi
        #   copy values
        clone.table$"Clone fraction" <- clone.table$"Adjusted clone fraction";
    }   #   fi

    #   write output to file
    output.file.name <- sub("[.][^.]*$", "", basename(input.file.path));
    if(remove.clone.table)  {
        output.file.name <- paste(output.file.name, "_postprocessed_removed.txt", sep="");
    }   else    {
        output.file.name <- paste(output.file.name, "_postprocessed.txt", sep="");
    }
	output.file.name <- file.path(dirname(input.file.path), output.file.name);

    write.table(clone.table, 
        file=output.file.name, 
        row.names=FALSE,
        sep="\t",
        quote=FALSE);

}   #   process.frameshifts.stop.codons()


#   This is the original function, which took as input.file.paths formatted for use in
#       VDJTools.  Such files had this schema:
#
#               #count  freq    cdr3nt  cdr3aa  v   d   j   VEnd    DStart  DEnd    JStart
#
#process.frameshifts.stop.codons <- function(input.file.path)    {
#
#    #   Specify characters to search for here.
#    #       Note that since "grep()" is used to identify records containing these
#    #       special characters, escapes may be required (e.g. "\\*" instead of "*").
#    special.characters <- c("\\*", "_");
#
#    #   read in file
#    clone.table <- read.delim(input.file.path, stringsAsFactors=FALSE);
#    #   identify records containing the special character
#    for(i in 1:length(special.characters))  {
#        aas <- clone.table$cdr3aa;
#        dirty.clone.indices <- integer();
#        dirty.clone.indices <- grep(special.characters[i], aas);
#        #   process.frameshifts.stop.codons
#        if(length(dirty.clone.indices > 0))   {
#            clone.table <- clone.table[-dirty.clone.indices,];
#        }   #   fi
#    }   #   for i 
#    #   write output to file
#
#    colnames(clone.table)[1] <- "#count";
#    output.file.name <- sub("[.][^.]*$", "", basename(input.file.path));
#    output.file.name <- paste(output.file.name, "_no_fssc.txt", sep="");
#
#    write.table(clone.table, 
#        file=output.file.name, 
#        row.names=FALSE,
#        sep="\t",
#        quote=FALSE);
#
#}   #   process.frameshifts.stop.codons()
#
